import 'package:iwork_project/models/autonomous_models.dart';
import 'package:iwork_project/models/descricao_models.dart';

class AutonomousRepository {
  final List<AutonomousModels> listaAvaliacao = [
    AutonomousModels(
      id: '1',
      name: 'José Amparo',
      autonomous: 'Pedreiro',
      description: DescricaoModels(
        id: '1',
        endereco: '123 Rua Principal, Popular Nova',
        descricao: 'Reparo de encanamento residencial.',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 9:00 AM - 5:00 PM',
        ratingEstrelas: 4.5,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '2',
      name: 'Carlinhos Maia',
      autonomous: 'Eletricista',
      description: DescricaoModels(
        id: '2',
        endereco: '456 Avenida Secundária, Clemente',
        descricao: 'Instalação elétrica e reparos.',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 8:00 AM - 6:00 PM',
        ratingEstrelas: 4.0,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '3',
      name: 'Amando Batista',
      autonomous: 'Pedreiro',
      description: DescricaoModels(
        id: '3',
        endereco: '789 Rua da Construção, Arpoador',
        descricao: 'Reparos e construção de alvenaria.',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 10:00 AM - 4:00 PM',
        ratingEstrelas: 4.2,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '4',
      name: 'Josoelton Silva',
      autonomous: 'Encanador',
      description: DescricaoModels(
        id: '4',
        endereco: '246 Rua das Cores, Tijuca',
        descricao: 'Pintura de paredes e móveis.',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 9:30 AM - 5:30 PM',
        ratingEstrelas: 4.7,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '5',
      name: 'Arnaldo Sacumani',
      autonomous: 'Carpinteiro',
      description: DescricaoModels(
        id: '5',
        endereco: '567 Avenida das Tubulações, Vila',
        descricao: 'Reparos de dutos e encanamentos.',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 8:30 AM - 6:30 PM',
        ratingEstrelas: 4.3,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '6',
      name: 'Zé do Pipo',
      autonomous: 'Jardineiro',
      description: DescricaoModels(
        id: '6',
        endereco: '101 Rua das Flores, Centro',
        descricao: 'Poda de árvores e plantas em geral.',
        tipoAtendimento: 'Residencial',
        horarioFuncionamento: 'Seg-Sex: 9:00 AM - 5:00 PM',
        ratingEstrelas: 4.9,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '7',
      name: 'Isabele',
      autonomous: 'Manicure',
      description: DescricaoModels(
        id: '7',
        endereco: 'Rua da Saudade, 416',
        descricao: 'Serviços de unha e pés',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sex: 8:00 AM - 5:30 PM',
        ratingEstrelas: 4.2,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '8',
      name: 'Jorge',
      autonomous: 'Cabeleireiro',
      description: DescricaoModels(
        id: '8',
        endereco: 'Rua da Saudade, 416',
        descricao: 'Serviços de cabelo',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sab: 8:00 AM - 6:30 PM',
        ratingEstrelas: 5.0,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '9',
      name: 'João',
      autonomous: 'Eletricista',
      description: DescricaoModels(
        id: '9',
        endereco: 'Rua da Saudade, 416',
        descricao: 'Serviços de cabelo',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sab: 8:00 AM - 6:30 PM',
        ratingEstrelas: 5.0,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '10',
      name: 'João',
      autonomous: 'Pintor',
      description: DescricaoModels(
        id: '10',
        endereco: 'Rua da Saudade, 416',
        descricao: 'Serviços de cabelo',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sab: 8:00 AM - 6:30 PM',
        ratingEstrelas: 5.0,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '11',
      name: 'Lucas',
      autonomous: 'Cabeleireiro',
      description: DescricaoModels(
        id: '11',
        endereco: 'Rua da Saudade, 416',
        descricao: 'Serviços de cabelo',
        tipoAtendimento: 'A domicílio',
        horarioFuncionamento: 'Seg-Sab: 8:00 AM - 6:30 PM',
        ratingEstrelas: 5.0,
        telefone: '(14) 995684-5548',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 995684-5548',
    ),
    AutonomousModels(
      id: '12',
      name: 'Guilherme Doretto',
      autonomous: 'Desenvolvedor',
      description: DescricaoModels(
        id: '12',
        endereco: 'Rua Santo Antonio, 122',
        descricao: 'Futuro formando da FATEC-Garça e desenvolvedor Flutter',
        tipoAtendimento: 'Home Office',
        horarioFuncionamento: 'Seg-Sab: 8:00 AM - 6:30 PM',
        ratingEstrelas: 5.0,
        telefone: '(14) 99871-1677',
      ),
      urlImage: 'assets/logo.png',
      telefone: '(14) 99871-1677',
    )
  ];

  getAutonomousByCategory(String categoria) {}
}
