name: iwork_project
description: App multiplataforma para pessoas autonomas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.8
  shared_preferences: ^2.0.6
  http: ^1.1.0
  modal_bottom_sheet: ^2.0.0
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  provider: ^6.0.1
  hive: ^2.0.4
  path_provider: ^2.0.2
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^4.9.3
  



flutter_native_splash:
  color: "#FE9C00"
  image: assets/vetor.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/vetor.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/newlogo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/

